### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sarah872** [epolevikov/Asgan#1]
Hi, thanks for the great tool!
Could you please give a bit more documentation to the output? E.g. what do the blue lines in the `adjacency_graph_query.gv` represent?

**Comment by epolevikov** [comment]
Hi,

The blue lines represent a path shared between the query and target graphs. For the test dataset, such a path is formed by the following sequence of edges: (-4, +3, -2, -1).

I'll add a more detailed documentation a bit later. For now, feel free to ask me if something is unclear.

**Comment by epolevikov** [comment]
Closing the issue. See the updated documentation. Feel free to reopen if you have any questions.
